DROP DATABASE IF EXISTS Housing;
CREATE DATABASE Housing; 
USE Housing; 
-- import `Housing`.`public_housing_inspection_data` csv using Wizard 
ALTER TABLE `Housing`.`public_housing_inspection_data`
MODIFY COLUMN INSPECTION_ID VARCHAR(10) PRIMARY KEY,
MODIFY COLUMN PUBLIC_HOUSING_AGENCY_NAME VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN COST_OF_INSPECTION_IN_DOLLARS INT,
MODIFY COLUMN INSPECTED_DEVELOPMENT_NAME VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN INSPECTED_DEVELOPMENT_ADDRESS VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN INSPECTED_DEVELOPMENT_CITY CHAR(50) DEFAULT NULL,
MODIFY COLUMN INSPECTED_DEVELOPMENT_STATE CHAR(2) DEFAULT NULL,
MODIFY COLUMN INSPECTION_DATE VARCHAR(50) DEFAULT NULL,
MODIFY COLUMN INSPECTION_SCORE INT;

-- update the inspection_date from string to date using the str_to_date function 
-- note that I set the INSPECTION_DATE as VARCHAR first before I use STR_TO_DATE function below
-- note the %m/%d/%Y format captial Y 	
UPDATE `Housing`.`public_housing_inspection_data`
SET INSPECTION_DATE = STR_TO_DATE(INSPECTION_DATE,'%m/%d/%Y');

SELECT * 
FROM `Housing`.`public_housing_inspection_data`; 

DROP TABLE IF EXISTS V1;
CREATE TABLE V1 AS 
SELECT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME ,INSPECTION_DATE AS MR_INSPECTION_DATE,COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE) AS SECOND_MR_INSPECTION_COST,
LAG(INSPECTION_DATE) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE) AS SECOND_MR_INSPECTION_DATE,
COST_OF_INSPECTION_IN_DOLLARS - LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE) AS CHANGE_IN_COST
FROM `public_housing_inspection_data`;

SELECT * 
FROM V1;

DROP TABLE IF EXISTS V2;
CREATE TABLE V2 AS
select * 
FROM V1
WHERE SECOND_MR_INSPECTION_COST IS NOT NULL AND CHANGE_IN_COST > 0; 

SELECT * 
FROM V2;

DROP TABLE IF EXISTS V3;
CREATE TABLE V3 AS 
SELECT *, ROW_NUMBER() OVER(PARTITION BY PHA_NAME ORDER BY PHA_NAME, MR_INSPECTION_DATE DESC) AS FLAG
FROM V2;

SELECT *
FROM V3;

DROP TABLE IF EXISTS V4;
CREATE TABLE V4 AS 
SELECT * 
FROM V3 
WHERE FLAG = 1; 

ALTER TABLE V4
DROP COLUMN flag; 

SELECT *
FROM V4;

DROP TABLE IF EXISTS V5;
CREATE TABLE V5 AS 
SELECT *, ((MR_INSPECTION_COST-SECOND_MR_INSPECTION_COST)/SECOND_MR_INSPECTION_COST)*100 AS PERCENT_CHANGE_IN_COST 
FROM V4;

SELECT * 
FROM V5;






